name: jojolo_mobile
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+5

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  get_it: ^7.2.0
  google_fonts: ^2.3.1
  http: ^0.13.4
  flutter_custom_tab_bar: ^1.1.9
  font_awesome_flutter: ^10.3.0
  dotted_border: any
  flutter_svg: any
  file_picker: ^4.5.1
  another_flushbar: ^1.10.28
  flutter_share: ^2.0.0
  flutter_cache_manager: ^3.3.0
  flutter_switch: ^0.3.2
  intl: ^0.17.0
  group_button: ^5.0.1
  path_provider:
  calendar_calendar: ^1.0.0
  socket_io_client: ^2.0.1
  like_button: ^2.0.4
  syncfusion_flutter_charts: ^19.1.54
  flutter_chat_bubble: ^2.0.0
  readmore: ^2.1.0
  flutter_countdown_timer: ^4.1.0
  flutter_local_notifications: any
  timezone: ^0.8.0
  flutter_paystack:
    git:
     url: https://github.com/definitelyme/flutter_paystack.git
     ref: a4a33c3dd0a12f46d655a2e63d11e9f20ba82d01


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.10.0"

  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app-icon.png"
  remove_alpha_ios: true